# Generated by Django 4.1 on 2024-05-30 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ply",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("video_path", models.CharField(blank=True, max_length=255, null=True)),
                ("flag", models.IntegerField(default=0)),
                ("ply_path", models.CharField(blank=True, max_length=255, null=True)),
                ("upload_time", models.DateTimeField(auto_now_add=True, null=True)),
                ("ply_time", models.DateTimeField(blank=True, null=True)),
                ("is_finished", models.IntegerField(default=0)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plys",
                        to="account.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "模型信息",
                "verbose_name_plural": "模型信息",
                "db_table": "ply",
            },
        ),
    ]
